version: '3.8'

services:
  db:
    image: postgres:13
    container_name: reminder_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reminder
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: reminder_bot
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DBNAME: reminder
      DATABASE_PORT: 5432
      DATABASE_SSLMODE: disable
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      BOT_TOKEN: "YOUR TOKEN"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
