apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-bot
  template:
    metadata:
      labels:
        app: reminder-bot
    spec:
      containers:
        - name: reminder-bot
          image: emelyanenkoig/reminder:1.0 # Замените на ваш образ
          env:
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_DBNAME
              value: "reminder"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_SSLMODE
              value: "disable"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: BOT_TOKEN
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reminder-bot
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: reminder-bot

---

apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
type: Opaque
data:
  BOT_TOKEN: "5621569001:AAF4zzjbRSON21P43bxgM95HLDGpr7WzZV8" # Замените на ваш закодированный токен
