### CONFIG FOR LOCAL DEBUG config.LoadLocalConfig()
database:
  host: localhost
  user: postgres
  password: postgres
  dbname: reminder
  port: 5432
  sslmode: disable

server:
  host: localhost
  port: 8080

bot:
  token: "YOUR TOKEN"
